#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 19 10:10:30 2017

@author: cookie040667
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 18 10:05:25 2017

@author: cookie040667
"""
i = int(input('please input num > 0 :'))
j = int(input('plese in put num < 1000000:'))

print ('(start :%d final :%d)' % (i,j))
m = 0

for n in range(i,j+1):
   print ('n=',n)
   count = []
   count.append(n)
   while n != 1:
      if n == 1:
         break
      elif n % 2 == 1:
         n = n*3+1
         count.append(n)
                  
      elif n % 2 == 0:
         n = n/2
         count.append(n)

   print(count)        
   print('result',len(count))
   if len(count) > m:
      m = len(count)
print(m)
   

   
   
